version: '3.6'
services:
  rshiny:
    image: "blackdoom/rshiny_packages_dependencies"
    container_name: rshiny
    ports:
      - 3838:3838
    volumes:
      - ./dependencies.sh:/home/dependencies.sh
      - ./packageInstaller.R:/home/packageInstaller.R
      - ./Libraries:/home/RLibz/
      - ./serverLog:/var/log/
      - ./Apps/server1/:/srv/shiny-server/
    tty: yes

    
